description: low level of stress testing
jobs:
  run-kernel-compile-host:
    exec: "bash"
    args: ["-c", "~/node-scripts/kernel-compile/run-kernel-compile.sh"]
  run-kernel-compile-container:
    exec: "bash"
    args: ["-c", "~/node-scripts/kernel-compile/run-kernel-compile-container.sh"]
